### ISSUE TITLE
Yui Compressor does not work on Windows

### ISSUE THREAD

**Issue by glen-84** [kriswallsmith/assetic#536]
I get the following error:

```
PHP Fatal error:  Uncaught exception 'Assetic\Exception\FilterException' with message 'An error occurred while running:
"java" "-jar" "D:\Programming\Git\x\x-website\config\autoload/../../tools/yuicompressor-2.4.8.jar" "-o" "C:\Windows\Temp\YUI2C0E.tmp" "--type" "css" "C:\Windows\Temp\YUI2BFD.tmp"

Error Output:
java.io.FileNotFoundException: WindowsTempYUI2C0E.tmp:\Windows\Temp\YUI2BFD.tmp (The filename, directory name, or volume label syntax is incorrect)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:208)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)


Input:
# in D:\Programming\Git\x\x-website\vendor\kriswallsmith\assetic\src\Assetic\Exception\FilterException.php on line 40
```

Could be related to issue #134 and #155

I'm using version 1.1.2.

**Comment by Maykonn** [comment]
Same here with 2.4.8 on Windows 10
