### ISSUE TITLE
Assettic ruby compass error

### ISSUE THREAD

**Issue by stilllife00** [kriswallsmith/assetic#708]
After configuring assetic (dev branch) on a new symfony 2.3 project with sass and compass filters , in the compiled CSS file I get this error

    /*
    [exception] 500 | Internal Server Error | Assetic\Exception\FilterException
    [message] An error occurred while running:
    '/home/mirko/.rvm/rubies/ruby-2.2.0/bin/ruby' '/home/mirko/.rvm/gems/ruby-2.2.0/bin/compass'     'compile' '/tmp' '--boring' '--images-dir' '/home/mirko/projects/evossc/app/../web/images' '--config' '/tmp/assetic_compassVgiDzq' '--sass-dir' '' '--css-dir' '' '/tmp/assetic_compassZMxL0j.scss'

    Error Output:
    /home/mirko/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could     not find 'compass' (>= 0) among 14 total gem(s) (Gem::LoadError)
    Checked in 'GEM_PATH=/tmp/.gem/ruby/2.2.0:/home/mirko/.rvm/rubies/ruby-2.2.0/lib/ruby/gems /2.2.0', execute `gem env` for more information
	from /home/mirko/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /home/mirko/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in  `gem'
	from /home/mirko/.rvm/gems/ruby-2.2.0/bin/compass:22:in `<main>'

gem list shows
     compass (1.0.3, 1.0.1)
so compass is there, I am using Ubuntu 14.04. This is the output of the `which` command

    which ruby
    /home/mirko/.rvm/rubies/ruby-2.2.0/bin/ruby
    which compass
    /home/mirko/.rvm/gems/ruby-2.2.0/bin/compass

Ruby and the gems are just installed with rvm. 

This is the Symfony config.yml relative part

    assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['EvoSscBundle']
    ruby:           /home/mirko/.rvm/rubies/ruby-2.2.0/bin/ruby
    filters:
        cssrewrite: ~
        sass:
            bin: /home/mirko/.rvm/gems/ruby-2.2.0/bin/sass
        compass:
            bin: /home/mirko/.rvm/gems/ruby-2.2.0/bin/compass 
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: /usr/bin/uglifyjs

**Comment by AJMiller** [comment]
@stilllife00 I had trouble getting assetic to load compass using a single-user install of rvm as well (installing to the home folder). Try reinstalling rvm using the multi-user install instructions and then install compass and update your paths in your config.yml

FWIW, you shouldn't need to specify your ruby path when using compass or sass. Those should be discovered automatically.
