### ISSUE TITLE
assetic:dump can't compile one file (yui-compressor)

### ISSUE THREAD

**Issue by Kraguesh** [kriswallsmith/assetic#762]
Hi all,

I have yui-compressor on a project Symfony 2 to minify my CSS/JSS. I have a problem when I dump for the prod environment.

I have one js file that generates an error. I thought it might be a conflict, so I compile it in a different block, but same problem. I need to delete the "?yui_js" filter to run the compilation. I tried with yui 2.4.7, same problem.

Error :

 [Assetic\Exception\FilterException]
  An error occurred while running:
  '/usr/bin/java' '-jar' '/var/www/adviz/app/Resources/java/yuicompressor-2.4.8.jar' '--charset' 'UTF-8' '-o' '/tmp/assetic_yui_outputHZBvlo' '--type' 'js' '/tmp/assetic_yui_inputlTs5wN'
  Error Output:
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    980:46:l'identifiant de propriété est incorrect
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    980:47:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    981:47:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    982:46:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    983:50:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    984:38:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1015:46:l'identifiant de propriété est incorrect
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1015:47:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1016:47:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1017:46:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1018:50:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1019:38:erreur de syntaxe
  [ERROR] in /tmp/assetic_yui_inputlTs5wN
    1:0:Compilation produced 12 syntax errors.
  org.mozilla.javascript.EvaluatorException: Compilation produced 12 syntax errors.
        at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)                                                                                                              
        at org.mozilla.javascript.Parser.parse(Parser.java:396)                                                                                                                                                
        at org.mozilla.javascript.Parser.parse(Parser.java:340)                                                                                                                                                
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)                                                                                                         
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)                                                                                                        
        at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)                                                                                                                        
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                                                                                         
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)                                                                                                                       
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                                                                               
        at java.lang.reflect.Method.invoke(Method.java:622)                                                                                                                                                    
        at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)                                                                                                                                 
  Input:

I can share my js if you need to check it. When I jslint my file, I don't have errors of syntax

Thanks !

**Comment by stof** [comment]
Well, maybe you have a syntax in yoru JS file which is not supported by YUICompressor. given that Yahoo deprecated their tool in favor of uglifyJS, it is totally possible that they don't support latest syntaxes.

**Comment by Kraguesh** [comment]
Yeah I confirm. 
Write this post help to find the problem :). I'll try uglify.

The property 'class' for append() is not supported by yuicompressor

Thanks.
